In [1]:
# Settings
data_dir = '/DATAPOOL/VPMB/BIDS-VPMB-SPE'
space_label = "MNI152NLin2009cAsym"
derivatives_folder = "derivatives/fmriprep23/fmriprep"
nilearn_folder = "derivatives/nilearn_glm/group"
#smoothing_fwhm = 6.0
#high_pass_hz = 0.003

In [16]:
task_label_list = ['AA','UA']
acq_label_list = ['0500','0750','1000','2500']
subject_list = ['sub-01',
                'sub-02',
                'sub-03',
                'sub-05',
                'sub-06',
                'sub-07',
                'sub-08',
                'sub-10',
                'sub-11',
                'sub-12',
                'sub-15',
                'sub-16',
                'sub-21',
                'sub-22',
                'sub-23']

In [21]:
# Import ROI values to a dataframe
import pandas as pd
import numpy as np
import os
import glob


# Create 3D dataframe with all the ROI values
df = pd.DataFrame(columns=['subject','beta','task','acq'])

# Loop over tasks and acquisitions
for task_label in task_label_list:
    for acq_label in acq_label_list:

        # contrast naming
        if task_label == "AA":
            contrast_name = "Ambiguous - Static"
            contrast_name_valid = "ambiguousMinusStatic"
        elif task_label == "UA":
            contrast_name = "Unambiguous - Static"
            contrast_name_valid = "unambiguousMinusStatic"

        # Get the beta values
        beta_file = os.path.join(data_dir,nilearn_folder,
                                 f"group_task-{task_label}_acq-{acq_label}_contrast-{contrast_name_valid}_c-bonferroni_p-0.05_clusterk-50_mean-beta-hMT-per-subject.tsv")
        
        beta_df = pd.read_csv(beta_file,sep='\t',header=None,names=['beta'])

        beta_df['subject'] = subject_list
        beta_df['task'] = task_label
        beta_df['acq'] = acq_label
        beta_df['beta'] = beta_df['beta'].astype(float)

        # Append to the dataframe
        df = df.append(beta_df,ignore_index=False)

/tmp/ipykernel_52618/595319337.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(beta_df,ignore_index=False)
/tmp/ipykernel_52618/595319337.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(beta_df,ignore_index=False)
/tmp/ipykernel_52618/595319337.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(beta_df,ignore_index=False)
/tmp/ipykernel_52618/595319337.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(beta_df,ignore_index=False)
/tmp/ipykernel_52618/595319337.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(beta_df,ignore_index=False)
/tmp/ipykernel_52618/595319337.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(beta_df,ignore_index=False)
/tmp/ipykernel_52618/595319337.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(beta_df,ignore_index=False)
/tmp/ipykernel_52618/595319337.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(beta_df,ignore_index=False)

In [22]:
beta_df

      beta subject task   acq
0   0.4660  sub-01   UA  2500
1   0.9228  sub-02   UA  2500
2   0.0940  sub-03   UA  2500
3   0.6395  sub-05   UA  2500
4   0.4247  sub-06   UA  2500
5   0.9411  sub-07   UA  2500
6   0.2792  sub-08   UA  2500
7   0.4514  sub-10   UA  2500
8   0.4564  sub-11   UA  2500
9   1.2324  sub-12   UA  2500
10  0.4607  sub-15   UA  2500
11  0.4565  sub-16   UA  2500
12  0.4341  sub-21   UA  2500
13  0.7494  sub-22   UA  2500
14  0.4703  sub-23   UA  2500

In [25]:
df

   subject    beta task   acq
0   sub-01  0.5176   AA  0500
1   sub-02  0.9419   AA  0500
2   sub-03  0.3601   AA  0500
3   sub-05  0.6652   AA  0500
4   sub-06  0.4056   AA  0500
..     ...     ...  ...   ...
10  sub-15  0.4607   UA  2500
11  sub-16  0.4565   UA  2500
12  sub-21  0.4341   UA  2500
13  sub-22  0.7494   UA  2500
14  sub-23  0.4703   UA  2500

[120 rows x 4 columns]